CREATE TABLE IF NOT EXISTS FACTORY_ROADMAP (
  id TEXT PRIMARY KEY,
  sequence_no INTEGER NOT NULL,
  title TEXT NOT NULL,
  job_type TEXT NOT NULL,
  agent_role TEXT NOT NULL,
  objective TEXT NOT NULL,
  acceptance_json TEXT NOT NULL DEFAULT '[]',
  depends_on_json TEXT NOT NULL DEFAULT '[]',
  payload_json TEXT NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'ready',
  work_queue_id TEXT,
  result_summary TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IX_FACTORY_ROADMAP_STATUS_SEQUENCE
ON FACTORY_ROADMAP(status,sequence_no);

CREATE TABLE IF NOT EXISTS QUALITY_REVIEWS (
  id TEXT PRIMARY KEY,
  job_id TEXT NOT NULL,
  run_id TEXT NOT NULL,
  reviewer_role TEXT NOT NULL,
  producer_model TEXT,
  reviewer_model TEXT,
  attempt_no INTEGER NOT NULL,
  decision TEXT NOT NULL,
  score REAL NOT NULL,
  reasons_json TEXT NOT NULL DEFAULT '[]',
  revision_instructions TEXT,
  deterministic_issues_json TEXT NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IX_QUALITY_REVIEWS_JOB
ON QUALITY_REVIEWS(job_id,created_at);

CREATE TABLE IF NOT EXISTS JOB_DECISIONS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  job_id TEXT NOT NULL,
  decision_type TEXT NOT NULL,
  actor_role TEXT NOT NULL,
  data_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
