CREATE TABLE IF NOT EXISTS PROJECT_IMPACT (
  id TEXT PRIMARY KEY,
  roadmap_id TEXT,
  job_id TEXT,
  impact_area TEXT NOT NULL,
  repo_full_name TEXT,
  branch_name TEXT,
  pr_number INTEGER,
  pr_url TEXT,
  status TEXT NOT NULL,
  summary TEXT NOT NULL,
  files_json TEXT NOT NULL DEFAULT '[]',
  qa_score REAL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_PROJECT_IMPACT_STATUS ON PROJECT_IMPACT(status,created_at);
CREATE INDEX IF NOT EXISTS IX_PROJECT_IMPACT_ROADMAP ON PROJECT_IMPACT(roadmap_id,created_at);

CREATE TABLE IF NOT EXISTS PROJECT_FEED_LOG (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  action TEXT NOT NULL,
  roadmap_id TEXT,
  detail_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_PROJECT_FEED_LOG_CREATED ON PROJECT_FEED_LOG(created_at);
